# Generated by Django 4.0.6 on 2022-08-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MrBeans', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
